# API
currency.api.url=https://open.er-api.com/v6/latest/EUR

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false